### ISSUE TITLE
[Bug Report] 运行崩溃

### ISSUE THREAD

**Issue by BlackLuny** [daeuniverse/dae-wing#155]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

运行崩溃。

### Expected Behavior

持续稳定运行。

### Steps to Reproduce

使用daed+dae-wing配置，运行一段时间dae-wing退出。

### Environment

- **Dae version (use `dae --version`)**: 
- dae-wing version 0.0.0.unknown git: a7252d92d0d19450cc39c1886e09d9fd98c5690e
- **OS (e.g `cat /etc/os-release`)**: 
- PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- **Kernel (e.g. `uname -a`)**:
- Linux debian 5.10.0-31-amd64 #1 SMP Debian 5.10.221-1 (2024-07-14) x86_64 GNU/Linux
- **Others**:

**Comment by BlackLuny** [comment]
[error_log.log](https://github.com/user-attachments/files/16606631/error_log.log)

**Comment by MarksonHon** [comment]
dae、dae-wing与daed只能同时运行一个
