### ISSUE TITLE
[Bug Report] build related: refused to build on mips after sqlite3 library change

### ISSUE THREAD

**Issue by kunish** [daeuniverse/dae-wing#21]
Check the daed project build step logs for details

https://github.com/daeuniverse/daed/actions/runs/5230019229/jobs/9443351141

**Comment by mzz2017** [comment]
One solution is that:

Go back to the previous behavior only for mips. That is to say, on mips, dae-wing does not support `CGO_ENABLED=0` and need user to install libsqlite3.

**Comment by kunish** [comment]
We do and should support as many platforms as we can, so as a matter of fact, the latter is the only option we should be choosing
