### ISSUE TITLE
[Feature Request] Add Scheduled Subscription Updates

### ISSUE THREAD

**Issue by QiuSimons** [daeuniverse/dae-wing#94]
As a user of the DAED, I would like to suggest the implementation of a new feature that allows for scheduled updates of subscription. Currently, the app requires manual updates for subscription, which can be cumbersome and time-consuming.

**Comment by yqlbu** [comment]
@QiuSimons Good suggestion indeed 👍

**Comment by QiuSimons** [comment]
似乎不是必要的功能了，可以利用curl曲线救国
https://github.com/QiuSimons/luci-app-daed/commit/4830b52
